apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-devops
  namespace: devops
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: "0.5"
    defaultRequest:
      memory: 128Mi
      cpu: "0.25m"
    type: Container
