apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: devops
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    secrets: 10
    count/configmap: 10
    count/deployments.apps: 5
    count/pods: 10

